# Generated by Django 5.0.2 on 2024-03-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
